substitutions:
  device_name: "esphome-keypad-debug"
  friendly_name: "Keypad-debug"

  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  enable_ipv6: "false"

  api_encryption_key: !secret api_encryption_key
  ota_password: !secret ota_password

  fp_password: "0x00000000"

  debug_mode: "1"
  api_reboot_timeout: "0s"

  log_level: "DEBUG"

packages:
  board:        !include keypad/board.yaml
  network:      !include keypad/network.yaml
  fingerprint:  !include keypad/fingerprint.yaml
  keypad:       !include keypad/keypad.yaml
  status_light: !include keypad/status_light.yaml
  debug:        !include keypad/debug.yaml

external_components:
  - source:
      type: local
      path: components
    components: [fingerprint_backup]
