from pathlib import Path

ROOT = Path(__file__).parent.parent
SECRETS_PATH = ROOT / "secrets.yaml"

CI_API_KEY = "MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE="

content = f"""\
# AUTO-GENERATED by tests/generate_test_secrets.py — for CI use only.
# Do NOT use these values outside of automated testing.
wifi_ssid: "ci_test_network"
wifi_password: "ci_test_password"
api_encryption_key: "{CI_API_KEY}"
ota_password: "ci_test_ota_password"
"""

SECRETS_PATH.write_text(content, encoding="utf-8")
print(f"Generated CI secrets: {SECRETS_PATH}")
